### ISSUE TITLE
Helix editor cannot register the lsp?

### ISSUE THREAD

**Issue by Ciflire** [ltex-plus/ltex-ls-plus#47]
**Describe the bug**
I am unsure if the lsp is the cause but i've been trying to make this work with helix. i'm getting the following warning
```
2024-11-08T23:27:08.133 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
```
if the concerned lsp is not mentionned i believe it is related to ltex ls as the other lsp i have configured works

**Steps to reproduce**
Use the following helix config for typst
```toml
[language-server.ltex-ls-plus]
command = "/nix/store/1125hnb9n9f1h2yhl6xiagl2gpc8qn12-ltex-ls-plus-18.3.0-alpha.nightly.2024-11-08/bin/ltex-ls-plus"

[language-server.tinymist]
command = "/nix/store/qarpsl8wm3yv2vhzdzlingqghn73ia3c-tinymist-0.12.0/bin/tinymist"

[[languages]]
auto-format = true
comment-token = "//"
file-types = ["typst", "typ"]
injection-regex = "typ(st)?"
language-servers = ["tinymist", "ltex-ls-plus"]
name = "typst"
scope = "source.typst"
```

This uses nix paths but don't mind those, the lsp is able to launch outside of helix. I get a java process running when the lsp is running, but i get non inside helix

**Expected behavior**
The expected behavior is to have the lsp working, giving error, and having the process running

**Version information**

- Operating system: Linux, NixOS
- ltex-ls: nightly build
- Java: 21.0.4

**Additional context/information**
https://github.com/valentjn/ltex-ls/issues/249
i found this issue that shows an helix example config, but as you can see, this is pretty close to mine
